name: fablab-printers-sim

services:
  printer-prn01:
    build:
      context: mock/printer-sim
      dockerfile: Dockerfile
    container_name: sim-printer-prn01
    environment:
      PRINTER_NAME: "PRN-01"
      PRINTER_MODEL: "MK4"
      PRINTER_SERIAL: "SIM-PRN01-SN"
    mac_address: "02:42:ac:19:00:11"
    networks:
      - imp3d_net
    restart: unless-stopped

  printer-prn02:
    build:
      context: mock/printer-sim
      dockerfile: Dockerfile
    container_name: sim-printer-prn02
    environment:
      PRINTER_NAME: "PRN-02"
      PRINTER_MODEL: "MK4S"
      PRINTER_SERIAL: "SIM-PRN02-SN"
    mac_address: "02:42:ac:19:00:12"
    networks:
      - imp3d_net
    restart: unless-stopped

  printer-prn03:
    build:
      context: mock/printer-sim
      dockerfile: Dockerfile
    container_name: sim-printer-prn03
    environment:
      PRINTER_NAME: "PRN-03"
      PRINTER_MODEL: "MINI+"
      PRINTER_SERIAL: "SIM-PRN03-SN"
    mac_address: "02:42:ac:19:00:13"
    networks:
      - imp3d_net
    restart: unless-stopped

networks:
  imp3d_net:
    external: true
    name: fablab_imp3d_net
