from __future__ import annotations

from typing import Protocol

from orchestrator.domain.models import DeviceRuntime, PrinterBinding, PrinterRuntime


class PrinterBindingRepositoryPort(Protocol):
    def list_all(self) -> list[PrinterBinding]: ...
    def get_by_printer_id(self, printer_id: str) -> PrinterBinding | None: ...
    def get_by_ip(self, printer_ip: str) -> PrinterBinding | None: ...
    def get_by_mac(self, printer_mac: str) -> PrinterBinding | None: ...
    def save(self, row: PrinterBinding) -> PrinterBinding: ...
    def delete(self, row: PrinterBinding) -> None: ...


class PrinterRuntimeRepositoryPort(Protocol):
    def list_all(self) -> list[PrinterRuntime]: ...
    def get_by_printer_id(self, printer_id: str) -> PrinterRuntime | None: ...
    def save(self, row: PrinterRuntime) -> PrinterRuntime: ...


class DeviceRuntimeRepositoryPort(Protocol):
    def list_all(self) -> list[DeviceRuntime]: ...
    def get_by_ip(self, device_ip: str) -> DeviceRuntime | None: ...
    def get_by_mac(self, device_mac: str) -> DeviceRuntime | None: ...
    def save(self, row: DeviceRuntime) -> DeviceRuntime: ...


class BackendGatewayPort(Protocol):
    def post_printer_state(self, printer_id: str, payload: dict) -> bool: ...

