from __future__ import annotations

from typing import Protocol

from orchestrator.application.dto import PrinterStateInput
from orchestrator.domain.models import Network, PrinterBinding


class PrinterBindingPersistencePort(Protocol):
    def list_all(self) -> list[PrinterBinding]: ...
    def get_by_id(self, binding_id: int) -> PrinterBinding | None: ...
    def get_by_printer_id(self, printer_id: str) -> PrinterBinding | None: ...
    def get_by_ip(self, printer_ip: str) -> PrinterBinding | None: ...
    def get_by_mac(self, printer_mac: str) -> PrinterBinding | None: ...
    def save(self, row: PrinterBinding) -> PrinterBinding: ...
    def delete(self, row: PrinterBinding) -> None: ...


class BackendGatewayPort(Protocol):
    def post_printer_state(self, printer_id: str, payload: dict) -> bool: ...


class PrinterAdapterPort(Protocol):
    def create_job(self, printer_ip: str, printer_file_path: str) -> str | None: ...
    def get_machine_info(self, printer_ip: str) -> dict: ...
    def get_machine_state(self, printer_ip: str) -> PrinterStateInput: ...


class PrinterAdapterResolverPort(Protocol):
    def get(self, adapter_name: str | None) -> PrinterAdapterPort | None: ...


class ArpNeighborScannerPort(Protocol):
    def scan(self, network: str, subnet_mask: str, timeout_s: float) -> dict[str, str]: ...


class DeviceProbeResultPort(Protocol):
    adapter_name: str
    reachable: bool
    model_hint: str | None
    serial_hint: str | None


class DeviceProberPort(Protocol):
    def probe(self, ip: str, timeout_s: float) -> DeviceProbeResultPort: ...


class DiscoverySnapshotPort(Protocol):
    def list_rows(self) -> list[dict[str, str | bool | int | float | None]]: ...
    def replace_rows(self, rows: list[dict[str, str | bool | int | float | None]]) -> None: ...
    def replace_from_network(self, network: Network) -> None: ...


class NotificationPort(Protocol):
    async def notify_device_rows(
        self,
        rows: list[dict[str, str | bool | int | float | None]],
    ) -> None: ...
    async def notify_external_rows(
        self,
        rows: list[dict[str, str | None]],
    ) -> None: ...

